# Generated by Django 6.0.2 on 2026-02-16 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HPCCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('host_type', models.CharField(choices=[('compute', 'compute'), ('infra', 'infra'), ('viz', 'viz')], default='compute', max_length=16)),
                ('status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('closed', 'closed')], default='available', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('idrac_host', models.CharField(max_length=255)),
                ('hw_model', models.CharField(max_length=255)),
                ('bios_version', models.CharField(max_length=255)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_status_change', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpc_hosts', to='inventory.hpccluster')),
            ],
            options={
                'indexes': [models.Index(fields=['cluster', 'host_type'], name='inventory_h_cluster_c207c1_idx'), models.Index(fields=['cluster', 'status'], name='inventory_h_cluster_5bcfcc_idx'), models.Index(fields=['hostname'], name='inventory_h_hostnam_81b6ff_idx')],
                'unique_together': {('cluster', 'hostname')},
            },
        ),
        migrations.CreateModel(
            name='SFANode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sfa', to='inventory.storagecluster')),
            ],
            options={
                'indexes': [models.Index(fields=['storage', 'role'], name='inventory_s_storage_141625_idx'), models.Index(fields=['hostname'], name='inventory_s_hostnam_d36cb4_idx')],
                'unique_together': {('storage', 'hostname'), ('storage', 'role')},
            },
        ),
        migrations.CreateModel(
            name='CESNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('notactive', 'notactive')], default='active', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_status_change', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ces', to='inventory.storagecluster')),
            ],
            options={
                'indexes': [models.Index(fields=['storage', 'status'], name='inventory_c_storage_568e43_idx'), models.Index(fields=['hostname'], name='inventory_c_hostnam_6970bd_idx')],
                'unique_together': {('storage', 'hostname')},
            },
        ),
    ]
