# Generated by Django 6.0.2 on 2026-02-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_host_location_host_quadrant_host_rack_host_shelf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='quadrant',
            new_name='quad',
        ),
    ]
