# Generated by Django 6.0.2 on 2026-02-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_quadrant_host_quad'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
