# Generated by Django 6.0.2 on 2026-02-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_host_asset_tag_host_serialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesnode',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cesnode',
            name='bios_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cesnode',
            name='host_type',
            field=models.CharField(choices=[('compute', 'compute'), ('infra', 'infra'), ('viz', 'viz')], default='compute', max_length=16),
        ),
        migrations.AddField(
            model_name='cesnode',
            name='hw_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cesnode',
            name='idrac_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cesnode',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cesnode',
            name='quad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cesnode',
            name='rack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cesnode',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cesnode',
            name='shelf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='bios_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
