# Generated by Django 6.0.2 on 2026-02-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_cesnode_asset_tag_cesnode_bios_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesnode',
            name='host_type',
            field=models.CharField(choices=[('compute', 'compute'), ('infra', 'infra'), ('viz', 'viz'), ('ces', 'ces')], default='compute', max_length=16),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_type',
            field=models.CharField(choices=[('compute', 'compute'), ('infra', 'infra'), ('viz', 'viz'), ('ces', 'ces')], default='compute', max_length=16),
        ),
    ]
