# Generated by Django 6.0.2 on 2026-02-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_cesnode_host_type_alter_host_host_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='kernal_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='os_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='used_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
