# Generated by Django 6.0.2 on 2026-02-19 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_host_kernal_version_host_os_type_host_used_for'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cesnode',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='cesnode',
            name='inventory_c_storage_568e43_idx',
        ),
        migrations.RemoveIndex(
            model_name='cesnode',
            name='inventory_c_hostnam_6970bd_idx',
        ),
        migrations.AlterUniqueTogether(
            name='sfanode',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='sfanode',
            name='inventory_s_storage_141625_idx',
        ),
        migrations.RemoveIndex(
            model_name='sfanode',
            name='inventory_s_hostnam_d36cb4_idx',
        ),
        migrations.AddField(
            model_name='hpccluster',
            name='cluster_type',
            field=models.CharField(choices=[('compute', 'compute'), ('infra', 'infra'), ('viz', 'viz'), ('ces', 'ces'), ('storage-infra', 'storage-infra')], default='hpc', max_length=16),
        ),
        migrations.AddField(
            model_name='hpccluster',
            name='storage_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storagecluster'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_type',
            field=models.CharField(choices=[('compute', 'compute'), ('infra', 'infra'), ('viz', 'viz'), ('ces', 'ces'), ('storage-infra', 'storage-infra')], default='compute', max_length=16),
        ),
        migrations.RemoveField(
            model_name='sfanode',
            name='storage',
        ),
        migrations.DeleteModel(
            name='CESNode',
        ),
        migrations.DeleteModel(
            name='SFANode',
        ),
    ]
