# Generated by Django 6.0.2 on 2026-02-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_cesnode_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
