# Generated by Django 6.0.2 on 2026-02-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_host_hostname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hpccluster',
            name='storage_details',
        ),
        migrations.DeleteModel(
            name='StorageCluster',
        ),
    ]
